[
  {
    "volumesFrom": [],
    "memory": 500,
    "extraHosts": null,
    "dnsServers": null,
    "disableNetworking": null,
    "dnsSearchDomains": null,
    "portMappings": [],
    "hostname": null,
    "essential": true,
    "entryPoint": null,
    "mountPoints": [],
    "name": "consul",
    "ulimits": null,
    "dockerSecurityOptions": null,
    "environment": [],
    "links": null,
    "workingDirectory": null,
    "readonlyRootFilesystem": null,
    "image": "consul:latest",
    "command": null,
    "user": null,
    "dockerLabels": null,
    "logConfiguration": null,
    "cpu": 0,
    "privileged": null,
    "memoryReservation": null
  }
]
